"""
Module for the collection of all needed constants.
"""
import os
import enum


__all__ = ["STATIC_DIR", "AdSource", "AdLocation"]


STATIC_DIR = os.path.join(os.getcwd(), 'static')


class AdSource(enum.Enum):
    """
    Enumeration class that provides the allowed source names.
    The API will use them for the input validations.
    """
    ADDRESSBG = "addressbg"
    ARCOREAL = "arcoreal"
    AVISTA = "avista"
    BULGARIANPROPERTIES = "bulgarianproperties"
    ERA = "era"
    GALARDO = "galardo"
    HOME2U = "home2u"
    IMOTBG = "imotbg"
    LUXIMMO = "luximmo"
    MIRELABG = "mirelabg"
    NOVDOM1 = "novdom1"
    PLACE2LIVE = "place2live"
    PRIMOPLUS = "primoplus"
    SUPERIMOTI = "superimoti"
    UES = "ues"
    YAVLENA = "yavlena"
    YOURHOME = "yourhome"


class AdLocation(enum.Enum):
    """
    Enumeration class that provides the allowed location names.
    The API will use them for the input validations.
    """
    SEDMI_11_KILOMETAR = "7-mi 11-ti kilometar"
    ABDOVICA = "Abdovica"
    BANISHORA = "Banishora"
    BELITE_BREZI = "Belite Brezi"
    BENKOVSKI = "Benkovski"
    BOROVO = "Borovo"
    BOTUNEC = "Botunec"
    BOTUNEC_2 = "Botunec 2"
    BOYANA = "Boyana"
    BUKSTON = "Bukston"
    VITOSHA = "Vitosha"
    VOENNA_RAMPA = "Voenna rampa"
    VRAJDEBNA = "Vrajdebna"
    VRABNICA_1 = "Vrabnica 1"
    VRABNICA_2 = "Vrabnica 2"
    Gevreliiski = "Gevreliiski"
    GEO_MILEV = "Geo Milev"
    GORNA_BANYA = "Gorna banya"
    GORUBLYANE = "Gorublyane"
    GOCE_DELCHEV = "Goce Delchev"
    GRADINA = "Gradina"
    DIANABAD = "Dianabad"
    DIMITAR_MILENKOV = "Dimitar Milenkov"
    DOKTORSKI_PAMETNIK = "Doktorski Pametnik"
    DRAGALEVCI = "Dragalevci"
    DRUJBA_1 = "Drujba 1"
    DRUJBA_2 = "Drujba 2"
    DURVENICA = "Durvenica"
    EKSPERIMENTALEN = "Eksperimentalen"
    ZAPADEN_PARK = "Zapaden park"
    ZAHARNA_FABRIKA = "Zaharna fabrika"
    ZONA_B18 = "Zona B-18"
    ZONA_B19 = "Zona B-19"
    ZONA_B5 = "Zona B-5"
    ZONA_B53 = "Zona B-5-3"
    IVAN_VAZOV = "Ivan Vazov"
    IZGREV = "Izgrev"
    IZTOK = "Iztok"
    ILINDEN = "Ilinden"
    ILIYANCI = "Iliyanci"
    KARPUZICA = "Karpuzica"
    KNYAJEVO = "Knyajevo"
    KRASNA_POLYANA_1 = "Krasna Polyana 1"
    KRASNA_POLYANA_2 = "Krasna Polyana 2"
    KRASNA_POLYANA_3 = "Krasna Polyana 3"
    KRASNO_SELO = "Krasno Selo"
    KREMIKOVCI = "Kremikovci"
    KRUSTOVA_VADA = "Krustova Vada"
    LAGERA = "Lagera"
    LEVSKI = "Levski"
    LEVSKI_V = "Vevski V"
    LEVSKI_G = "Levski G"
    LETISHTE_SOFIYA = "Letishte Sofiya"
    LOZENEC = "Lozenec"
    LULIN = "Lulin"
    LULIN_1 = "Lulin 1"
    LULIN_2 = "Lulin 2"
    LULIN_3 = "Lulin 3"
    LULIN_4 = "Lulin 4"
    LULIN_5 = "Lulin 5"
    LULIN_6 = "Lulin 6"
    LULIN_7 = "Lulin 7"
    LULIN_8 = "Lulin 8"
    LULIN_9 = "Lulin 9"
    LULIN_10 = "Lulin 10"
    MALASHEVCI = "Malashevci"
    MALINOVA_DOLINA = "Malinova Dolina"
    MANASTIRSKI_LIVADI = "Manastirski Livadi"
    MEDICINSKA_AKADEMIYA = "Medicinska Akademiya"
    MLADOST_1 = "Mladost 1"
    MLADOST_1A = "Mladost 1A"
    MLADOST_2 = "Mladost 2"
    MLADOST_3 = "Mladost 3"
    MLADOST_4 = "Mladost 4"
    MODERNO_PREDGRADIE = "Moderno Predgradie"
    MUSAGENICA = "Musagenica"
    NADEJDA_1 = "Nadejda 1"
    NADEJDA_2 = "Nadejda 2"
    NADEJDA_3 = "Nadejda 3"
    NADEJDA_4 = "Nadejda 4"
    OBELYA = "Obelya"
    OBELYA_1 = "Obelya 1"
    OBELYA_2 = "Obelya 2"
    OBORISHTE = "Oborishte"
    OVCHA_KUPEL = "Ovcha Kupel"
    OVCHA_KUPEL_1 = "Ovcha Kupel 1"
    OVCHA_KUPEL_2 = "Ovcha Kupel 2"
    ORLANDOVCI = "Orlandovci"
    PAVLOVO = "Pavlovo"
    PODUYANE = "Poduyane"
    POLIGONA = "Poligona"
    RAZSADNIKA = "Razsadnika"
    REDUTA = "Reduta"
    REPUBLIKA = "Republika"
    REPUBLIKA_2 = "Republika 2"
    SVETA_TROICA = "Sveta Troica"
    SVOBODA = "Svoboda"
    SERDIKA = "Serdika"
    SIMEONOVO = "Simeonovo"
    SLAVIYA = "Slaviya"
    SLATINA = "SLATINA"
    STRELBISHTE = "Strelbishte"
    STUDENTSKI_GRAD = "Studentski grad"
    SUHATA_REKA = "Suhata reka"
    SUHODOL = "Suhodol"
    TOLSTOI = "Tolstoi"
    TREBICH = "Trebich"
    TRIAGALNIKA = "Triagalnika"
    FAKULTETA = "Fakulteta"
    FILIPOVCI = "Filipovci"
    FONDOVI_JILISHTA = "Fondovi Jilishta"
    HADJI_DIMITAR = "Hadji Dimitar"
    HIPODRUMA = "Hipodruma"
    HLADILNIKA = "Hladilnika"
    HRISTO_BOTEV = "Hristo Botev"
    CENTAR = "Centar"
    YAVOROV = "Yavorov"
