"""
Module for the collection of all needed constants.
"""
import os
import enum


__all__ = ["STATIC_DIR", "AdSource", "AdLocation"]


STATIC_DIR = os.path.join(os.getcwd(), 'static')


class AdSource(enum.Enum):
    """
    Enumeration class that provides the allowed source names.
    The API will use them for the input validations.
    """
    ADDRESSBG = "addressbg"
    ARCOREAL = "arcoreal"
    AVISTA = "avista"
    BULGARIANPROPERTIES = "bulgarianproperties"
    ERA = "era"
    GALARDO = "galardo"
    HOME2U = "home2u"
    IMOTBG = "imotbg"
    LUXIMMO = "luximmo"
    MIRELABG = "mirelabg"
    NOVDOM1 = "novdom1"
    PLACE2LIVE = "place2live"
    PRIMOPLUS = "primoplus"
    SUPERIMOTI = "superimoti"
    UES = "ues"
    YAVLENA = "yavlena"
    YOURHOME = "yourhome"
    BEZKOMISIONA = "bezkomisiona"


class HomeType(enum.Enum):
    """
    Enumeration class that provides the allowed home types.
    The API will use them for the input validations.
    """
    EDNOSTAEN = "Едностаен"
    DVISTAEN = "Двустаен"
    TRISTAEN = "Тристаен"
    MNOGOSTAEN = "Многостаен"
    STUDIO = "Студио"
    MEZONET = "Мезонет"


class AdLocation(enum.Enum):
    """
    Enumeration class that provides the allowed location names.
    The API will use them for the input validations.
    """
    SEDMI_11_KILOMETAR = "7-ми 11-ти километър"
    ABDOVICA = "Абдовица"
    BANISHORA = "Банишора"
    BELITE_BREZI = "Белите Брези"
    BENKOVSKI = "Бенковски"
    BOROVO = "Борово"
    BOTUNEC = "Борунец"
    BOTUNEC_2 = "Ботунец 2"
    BOYANA = "Бояна"
    BUKSTON = "Бъкстон"
    VITOSHA = "Витоша"
    VOENNA_RAMPA = "Военна Рампа"
    VRAJDEBNA = "Враждебна"
    VRABNICA_1 = "Връбница 1"
    VRABNICA_2 = "Връбница 2"
    Gevreliiski = "Геврелийски"
    GEO_MILEV = "Гео Милев"
    GORNA_BANYA = "Горна Баня"
    GORUBLYANE = "Горубляне"
    GOCE_DELCHEV = "Гоце Делчев"
    GRADINA = "Градина"
    DIANABAD = "Дианабад"
    DIMITAR_MILENKOV = "Димитър Миленков"
    DOKTORSKI_PAMETNIK = "Докторски паметник"
    DRAGALEVCI = "Драгалевци"
    DRUJBA_1 = "Дружба 1"
    DRUJBA_2 = "Дружба 2"
    DURVENICA = "Дървеница"
    EKSPERIMENTALEN = "Експериментален"
    ZAPADEN_PARK = "Западен парк"
    ZAHARNA_FABRIKA = "Захарна фабрика"
    ZONA_B18 = "Зона Б-18"
    ZONA_B19 = "Зона Б-19"
    ZONA_B5 = "Зона Б-5"
    ZONA_B53 = "Зона Б-5-3"
    IVAN_VAZOV = "Иван Вазов"
    IZGREV = "Изгрев"
    IZTOK = "Изток"
    ILINDEN = "Илинден"
    ILIYANCI = "Илиянци"
    KARPUZICA = "Карпузица"
    KNYAJEVO = "Княжево"
    KRASNA_POLYANA_1 = "Красна поляна 1"
    KRASNA_POLYANA_2 = "Красна поляна 2"
    KRASNA_POLYANA_3 = "Красна поляна 3"
    KRASNO_SELO = "Красно село"
    KREMIKOVCI = "Кремиковци"
    KRUSTOVA_VADA = "Кръвтова вада"
    LAGERA = "Лагера"
    LEVSKI = "Левски"
    LEVSKI_V = "Левски В"
    LEVSKI_G = "Левски Г"
    LETISHTE_SOFIYA = "Летище София"
    LOZENEC = "Лозенец"
    LULIN = "Люлин"
    LULIN_1 = "Люлин 1"
    LULIN_2 = "Люлин 2"
    LULIN_3 = "Люлин 3"
    LULIN_4 = "Люлин 4"
    LULIN_5 = "Люлин 5"
    LULIN_6 = "Люлин 6"
    LULIN_7 = "Люлин 7"
    LULIN_8 = "Люлин 8"
    LULIN_9 = "Люлин 9"
    LULIN_10 = "Люлин 10"
    MALASHEVCI = "Малашевци"
    MALINOVA_DOLINA = "Малинова долина"
    MANASTIRSKI_LIVADI = "Манастирски ливади"
    MEDICINSKA_AKADEMIYA = "Медицинска академия"
    MLADOST_1 = "Младост 1"
    MLADOST_1A = "Младост 1A"
    MLADOST_2 = "Младост 2"
    MLADOST_3 = "Младост 3"
    MLADOST_4 = "Младост 4"
    MODERNO_PREDGRADIE = "Модерно предградие"
    MUSAGENICA = "Мусагеница"
    NADEJDA_1 = "Надежда 1"
    NADEJDA_2 = "Надежда 2"
    NADEJDA_3 = "Надежда 3"
    NADEJDA_4 = "Надежда 4"
    OBELYA = "Обеля"
    OBELYA_1 = "Обеля 1"
    OBELYA_2 = "Обеля 2"
    OBORISHTE = "Оборище"
    OVCHA_KUPEL = "Овча купел"
    OVCHA_KUPEL_1 = "Овча купел 1"
    OVCHA_KUPEL_2 = "Овча купел 2"
    ORLANDOVCI = "Орландовци"
    PAVLOVO = "Павлово"
    PODUYANE = "Подуяне"
    POLIGONA = "Полигона"
    RAZSADNIKA = "Разсадника"
    REDUTA = "Редута"
    REPUBLIKA = "Република"
    REPUBLIKA_2 = "Република 2"
    SVETA_TROICA = "Света троица"
    SVOBODA = "Свобода"
    SERDIKA = "Сердика"
    SIMEONOVO = "Симеоново"
    SLAVIYA = "Славия"
    SLATINA = "Слатина"
    STRELBISHTE = "Стрелбище"
    STUDENTSKI_GRAD = "Студентски град"
    SUHATA_REKA = "Сухата река"
    SUHODOL = "Суходол"
    TOLSTOI = "Толстой"
    TREBICH = "Требич"
    TRIAGALNIKA = "Триъгълника"
    FAKULTETA = "Факултета"
    FILIPOVCI = "Филиповци"
    FONDOVI_JILISHTA = "Фондови жилища"
    HADJI_DIMITAR = "Хаджи Димитър"
    HIPODRUMA = "Хиподрума"
    HLADILNIKA = "Хладилника"
    HRISTO_BOTEV = "Христо Ботев"
    CENTAR = "Център"
    YAVOROV = "Яворов"
